CC := vc +aosppc
#CC := gcc -std=c99
CFLAGS := -D__USE_INLINE__
LIBS := -lamiga

OBJS := avalanche.o libs.o xad.o
DEPS := avalanche_rev.h avalanche.h libs.h xad.h

all: AvalanchePPC install

%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) -c -o $@ $<

AvalanchePPC: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)

install: AvalanchePPC
	copy AvalanchePPC /

clean:
	delete #?.o
	delete AvalanchePPC
