CC := vc +aosppc
#CC := gcc -std=c99
CFLAGS := -D__USE_INLINE__ -ISDK:local/common/include
LIBS := -lamiga

OBJS := avalanche.o libs.o req.o xad.o xfd.o xvs.o
DEPS := avalanche_rev.h avalanche.h libs.h req.h xad.h xfd.h xvs.h

all: AvalanchePPC

%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) -c -o $@ $<

AvalanchePPC: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)

install: AvalanchePPC
	copy AvalanchePPC /

clean:
	delete #?.o
	delete AvalanchePPC
