on:
  push:
    branches: [ main, autobuild ]
  pull_request:
    branches: [ main, autobuild ]
 
jobs:
  build_ppc:
    runs-on: ubuntu-latest
    container:
      image: walkero/docker4amigavbcc:latest-ppc
    name: build_os4
    steps:
      - uses: actions/checkout@v2
      - name: build_os4
        id: build_os4
        run: |
          cd ./src
          make -f Makefile.cross AvalanchePPC
      - uses: actions/upload-artifact@v4
        with:
          name: AvalanchePPC
          path: ./src/os4/AvalanchePPC
  build_68k:
    runs-on: ubuntu-latest
    container:
      image: walkero/docker4amigavbcc:latest-m68k
    name: build_os3
    steps:
      - uses: actions/checkout@v2
      - name: build_os3
        id: build_os3
        run: |
          cd ./src
          make -f Makefile.cross Avalanche
      - uses: actions/upload-artifact@v4
        with:
          name: Avalanche
          path: ./src/os3/Avalanche
